#!/bin/bash
rm temp.txt
touch temp.txt
cat processInfo | tr '\r\n' '::' | sed -r 's/[ ]+/ /g' | sed 's/<td>//g' | sed 's/<\/td>//gp' | sed 's/:: :: :: /:/gp' | sed 's/: /\n/gp' | grep -P "^[0-9]{2}\/[0-9]{2}\/[0-9]{4}" > temp.txt
rm processInfo
